### ISSUE TITLE
not installing via sketch runner

### ISSUE THREAD

**Issue by jimboroberts** [mcansh/squash-sketchplugin#2]
Hi,

Your plugin doesn't seem to be instaling via Runner.
I also can't get the latest release to run either. Not sure if this is still supported or not.

**Comment by mcansh** [comment]
Hi @jimboroberts, it's been a bit since I've used this plugin, but I can take a look this week and see if I can get it to work or at least narrow down where it's broken.

**Comment by mcansh** [comment]
hey @jimboroberts, I bumped the dependencies and also noticed that you need to tell sketch you want to export the file, lemme know if https://github.com/mcansh/squash-sketchplugin/releases/tag/1.0.2-canary.0 fixes it for you 😄

also occasionally squash will crash while trying to open the file passed, not sure if there's anything I can do in the plugin though.

**Comment by mcansh** [comment]
here's a [quick demo](https://sketch-squash-issue-2.mcansh1.now.sh), squash itself seems pretty _broken_ on macOS Catalina
